/**:
  ros__parameters:
    wheel_radius: 0.15 # The radius of the wheel, primarily used for dead reckoning.
    wheel_width: 0.03 # The lateral width of a wheel tire, primarily used for dead reckoning.
    wheel_base: 0.45 # between front wheel center and rear wheel center
    wheel_tread: 0.45 # between left wheel center and right wheel center
    front_overhang: 0.45 # between front wheel center and vehicle front
    rear_overhang: 0.15 # between rear wheel center and vehicle rear
    vehicle_width: 0.50
    vehicle_length: 0.60  # front_overhang + rear_overhang
    vehicle_height: 0.50
    #caster_wheel_radius: 0.08
    left_overhang: 0.060 # between left wheel center and vehicle left
    right_overhang: 0.060 # between right wheel center and vehicle right
    max_steer_angle: 0.70 # [rad]
